# Generated by Django 3.2.9 on 2021-12-06 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorias', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Platillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('maxExtras', models.IntegerField()),
                ('precio', models.FloatField()),
                ('imagen', models.ImageField(null=True, upload_to='platillos')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platillos', to='orders.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('cantidadPlatillos', models.IntegerField()),
                ('precioPlatillos', models.FloatField()),
                ('extras', models.ManyToManyField(blank=True, to='orders.Extra')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='orders.pedido')),
                ('platillo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.platillo')),
            ],
        ),
    ]
